name: build-test
on:
  push:
    branches: [main]

jobs:
  checks:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run unit tests with coverage
        run: |
          SUMMARY="$(npm run test:cov --coverageReporters=text-summary | tail -3 | head -1)"
          TOKENS=($SUMMARY)
          echo "COVERAGE=$(echo ${TOKENS[2]})" >> $GITHUB_ENV
      - name: Run e2e tests
        run: npm run test:e2e
